### PR TITLE
de.lua for Rep

### PR DESCRIPTION
**Pull request by Staubgeborener**
First attempt for german rep translation

### CODE REVIEW

**Comment by Staubgeborener** [comment]
Don't merge yet, I need one or two more days.

**Comment by Staubgeborener** [comment]
This is ready so far.

**Notes:**

- Poop = Kot or Kacke? Right now it's both.

- "Leeren von Räumen" = was a workaround to translate "clear a room" reasonably.

- -- Lil Clot = Leave it as "Lil Clot" or "Lil Gerinnsel" or "Kleines Gerinnsel"? There are some more "lil" items that should somehow stay in the same pattern.

- active Item = active Item or translate into german?


All in all: Denglish often seems to me to be a good way. While we're talking about this subject: I would prefer a `de_english.lua` variant, where the descriptions are in German, but the English item name is retained.

**Comment by itsFelixH** [comment]
To your notes:

- I'd prefer "Kacke". It's less serious than "Kot".
- "Raum abschließen" maybe? Other opions are "Raum räumen", "Raum beenden", "Raum besiegen" or longer "Raum fertig machen"?
- "Kleines Gerinnsel" since it is less Denglish. Lil = Klein?
- "Aktiver Gegenstand" does not sound good, maybe "Aktives Item"

I also would prefer your suggested `de_english.lua` Version!

**Comment by Staubgeborener** [comment]
> I'd prefer "Kacke". It's less serious than "Kot".

Me too. `Tötet sofort Kackfeinde und Bosse`. This translation is hilarious.

> "Kleines Gerinnsel" since it is less Denglish. Lil = Klein?

In this case, we should translate everything that has "lil" in its name into "Klein". But that ruins the [hip hop flair](https://www.highsnobiety.com/p/lil-rappers-ranking-2/).

> "Aktiver Gegenstand" does not sound good, maybe "Aktives Item"

I have called it as "active item" for now.  Everything else currently seems too tryhard to me and reminds me of some German subreddits.

**Comment by Staubgeborener** [comment]
> I also would prefer your suggested de_english.lua Version!

As soon as this one is merged, I will use this new `de.lua` file as a template for a `de_english.lua` version. I have left the original commentaries at the end of each line, so I should be able to automate this somehow.

**Comment by Staubgeborener** [comment]
@wofsauge You can check it and merge it if it fits. As I said, I would make a `de_english.lua` version, probably this year (English original item names but German descriptions). I will create a new branch and open a new PR for this.

**Comment by kohashiwakaba** [comment]
If you only want to see english names, `de_english.lua` is not needed because EID already has an option to set names to english.

The setting is in:
`EID.Config.TranslateItemName` in eid_config.lua
or
`EID > General > Name Language` in Mod Config Menu

**Comment by Staubgeborener** [comment]
@kohashiwakaba Thanks, if this works - great! The [ab+ de.lua](https://github.com/wofsauge/External-Item-Descriptions/blob/master/descriptions/ab%2B/de.lua) already has English names and German descriptions. This should be standardized independently of the Mod Config Menu - either all names in German, or all names in English. One of the two translations should be adapted accordingly.

**Comment by kohashiwakaba** [comment]
EID is supposed to run at least in AB+ DLC and Repentance data will override AB+ if running on Repentance DLC. 

Anyways I've found AB+ German language pack is not even finished (basically every entries in en_us should be translated), probably that's the reason of English names in German language pack.

**Comment by wofsauge** [comment]
Great work with the translation so far :) 
ive fixed a few issues so that its actually useable in the game. 

would be cool if you can also translate the AB+ file, which acts as the default translation for items.

**Comment by Staubgeborener** [comment]
@wofsauge 
> would be cool if you can also translate the AB+ file, which acts as the default translation for items.

I'm in NYC right now for vacation, maybe i will translate the other stuff by the end of this year.

**Comment by wofsauge** [comment]
Sounds good. Have fun on your vacation :)

**Pull request merged**
