### PR TITLE
Remove Tear Height from Repentance

### PR DESCRIPTION
**Pull request by Buurazu**
I was always noticing that the "tear height" increases didn't seem to mean anything in Repentance, and with further testing, indeed they don't.
The TearHeight attribute of the player is only changed by two items as far as I can tell; Number One, and Tape Worm (and Tape Worm is probably a bug from halving it in AB+). It's just a visual thing of where the tear comes from on your sprite, which has no impact on effective range anymore, but does have an impact on initial tear falling speed, as it has to fall a lot faster if it has high height.
The ability for a tear to gain height after being shot, flying over obstacles if high enough, is entirely tied to the reworked Range stat. It can be tested with a mod that lets you set your stats; setting range to 40 gives the exact same tears as giving yourself a bunch of Mom's Heels or other (formerly) tear height increasing item.
In fact, once everything is calculated, the TearRange stat isn't used at all when actually firing tears. All that matters is TearFallingSpeed, which seems to be calculated using ShotSpeed, TearRange, TearHeight (usually 23.75), and TearFallingAcceleration (usually 0; most noticeably changed with Ipecac style tears).
Anyway, I say with absolute confidence that removing tear height in Repentance's descriptions is correct, and I reported the Tape Worm bug :)

### CODE REVIEW

**Comment by wofsauge** [comment]
The tear height change needs to be tested. In the past, There where instances where users complained that this stat change was not listed in the description of an item. despite it had little gameplay relevant impact even back in ab+.
Im therefore hesitant to remove it entirely.

**Comment by Buurazu** [comment]
I've downgraded to AB+ to test what exactly is going on there, and it might complicate things more; "tear height" is completely misnamed. It's tear falling speed that's modified.

In AB+, Player.TearHeight is always equal to the range stat, but negative. So Range = Tear Height. I don't think there's anything more to the visual range stat than that. Give yourself 20 Mom's Heels and your tears will be flying out from way above Isaac's head. It looks stupid, although whether it's stupider than Repentance tears starting at the eyes and flying upwards is personal preference.

And then the distance that a tear actually travels depends on Shot Speed, and the hidden Tear Falling Speed attribute. Player.TearFallingSpeed is what all the Tear Height stat boosts match, and the numbers in EID that I've checked are accurate. Lazy Worm gives +2 Tear Falling Speed. Tape Worm halves Tear Falling Speed. Mom's Heels gives +0.5 Tear Falling Speed. Number One gives +0.76 Tear Falling Speed.
Note that positive "falling" speeds are good and means the tear will move upwards when initially fired. That initial upward speed gradually accelerates downwards. So, it's a combination of Range (initial height), Shot Speed (horizontal speed), and Tear Falling Speed (vertical speed, with Tear Falling Acceleration + gravity applied over time) that give you your effective range, and items modify all 3 of these.

"+0.5 Tear Falling Speed" wouldn't work at all though since it sounds like it'd make tears go down faster, and tear height in AB+ is pretty established, so renaming the stat is pointless. But I'm happy to be able to see the difference it makes, to see the supposed numbers indeed getting added.

But anyway, knowing how AB+'s range works, I'm still just as certain that "+0.5 Tear Height"s do not exist in Repentance's proper "range = tiles traveled" system. I do not believe any items directly touch Tear Falling Speed anymore; Tear Falling Speed is calculated based on the new Tear Range stat, Tear Height (only changed by Number One / Tape Worm), and Tear Falling Acceleration + gravity.

**Comment by wofsauge** [comment]
hmm interesting... didnt know it was that convoluted of a stat.

Since you say that the Tear Height is not used anymore in Rep, i would say that your idea with removing that stat all together seems reasonable.

What do you think, should it still be removed?

**Comment by Buurazu** [comment]
I am 100% sure there is no Tear Height being modified in Repentance except for Number One-like visual effects (and I'm not sure if there's any others like that)
I also checked every Range Up item in AB+ while I had it open and added a few more tear heights to that for completeness

**Pull request merged**
