### PR TITLE
ko_kr : Updated descriptions / Spindown Dice Result additions

### PR DESCRIPTION
**Pull request by kohashiwakaba**
- Eye Drops(600): After some testing, Eye Drops does not actually make left eye +28% Fire Rate up. Instead, it increases +20% Fire Rate up, then +16.67% additional Fire Rate up for Left eye.
- Added status effect icons
(Ignore some commits, they do nothing)

### CODE REVIEW

**Comment by kohashiwakaba** [comment]
- Added Spindown Dice List options(IDs/names, both are disabled by default)
- Adjusted Spindown Dice List for Dad's Note. List will stop at Dad's note regardless of options.

**Comment by Buurazu** [comment]
I did testing on Eye Drops and it has absolutely no effect on the left eye, at least if you have both eyes shooting. Tainted ??? + Eve's Mascara had a 1466 or 1500ms fire delay; with Eye Drops, left eye was 1466 or 1500ms, right eye was 1033 or 1066ms

**Comment by kohashiwakaba** [comment]
After receiving the comment, I've did some further testing with co-op controller, and found some interesting things.
- Isaac tends to shoot Left Eye first, This means Isaac shoots L first, R after 10 frames, and L after 20 frames, and so on.
 Left Eye : (0, 20, 40...)
 Right Eye : (10, 30, 50...)
- For 10 MaxFireDelay(Isaac's basic stat), acquiring Eye Drops actually makes Left eye shoot per 14~15 frames rather than 20 frames.
- Right eye will now shoot as Left Eye did(10, 30, 50... -> 0, 20, 40... after Eye Drops acquired), **but This is after +20% Fire rate up, so right eye has increased Fire Delay in contrast to left eye.**
- Non-Tear weapons(Such as Azazel) actually get benefit from Eye Drops. For them, this item just acts as Fire Delay up item.

Only tested with Isaac, T.???, and Azazel. Although the results was same pattern as below, further testing is needed. But at least Desc of Eye Drops should be:

- +20% Fire Rate up
- +??% additional Fire Rate up for Left Eye
- -??% additional Fire Rate Down for Right Eye

https://user-images.githubusercontent.com/37092106/152676512-cfffa82d-468f-43aa-b6cc-3aafa826d832.mp4

**Comment by Buurazu** [comment]
I'm afraid I have no idea what you're claiming your video proves. All it proves is that for every other shot of the bottom Isaac, there's a matching tear on the top Isaac. As it should be, because the top Isaac only has one eye out of sync.

Based on the way that you can get a double shot if you wait, I'm guessing that Eye Drops' effect basically makes Isaac have two separate fire delays, one for each eye, that are handled individually. And one of those has a ~28% faster fire rate.

+20% fire rate does seem to be what it does if it can't do the one-eye-only effect.

**Pull request merged**
