### PR TITLE
Description updates, changes, fixes

### PR DESCRIPTION
**Pull request by Ma-rcx**
A bunch of changes and fixes:

- Red Hearts are properly uppercased
- Added ↑ arrow before e.g. "+1 Health up"
- Replace some chance numbers with percentages
- Clean up and change a bunch of descriptions
- Update/fix some descriptions

and probably more that I forgot 😄

### CODE REVIEW

**Comment by Buurazu** [comment]
this removes a lot of the tear chance percentages I added on collectibles D:

**Comment by Ma-rcx** [comment]
> this removes a lot of the tear chance percentages I added on collectibles D:

It does? I'm sorry about that. Thought it would look a bit cleaner, but I'm just going to reverse my changes if that's alright.

**Comment by Buurazu** [comment]
Looks good now except for Explosivo; the stuck tears don't do damage periodically, just normal damage on initial contact (that's something else I updated while datamining the percentage)
I was on the fence with how to do the 1/6 chances cause 16.66% looked bad, 17% is probably best

**Comment by Ma-rcx** [comment]
> Looks good now except for Explosivo; the stuck tears don't do damage periodically, just normal damage on initial contact (that's something else I updated while datamining the percentage) I was on the fence with how to do the 1/6 chances cause 16.66% looked bad, 17% is probably best

I don't know why I changed that about Explosivo, wasn't thinking straight lol, anyway I'll fix that as well

**Comment by Buurazu** [comment]
I suppose it is, although Explosivo has been historically awful because it doesn't deal regular damage on hit, so people that don't know about the repentance buff yet might still avoid it if it's not explicitly stated

**Pull request merged**
