### PR TITLE
Add turkish translation

### PR DESCRIPTION
**Pull request by cagdassalur**
- language was named "turkish" for some reason, changed it to "tr_tr" hope you don't mind.
- Do you have a list of unique items between ab+ and rep? Right now i only wanted to support rep and only changed that folder, later realizing i have to translate a lot in the ab+ dir as well. That is untouched at the moment.

edit: I noticed that only 100 or so items for ab+ were translated and some of them were incorrect so i duplicated en_us and translated for scratch. Skipped all the items that has changed descriptions on repentance.

### CODE REVIEW

**Comment by wofsauge** [comment]
Hi. I dont have a direct list, but the changes item ids are all grouped inside the repentance translation file. There are empty lines that divide the ab+ changes from the new rep content

**Comment by cagdassalur** [comment]
> Hi. I dont have a direct list, but the changes item ids are all grouped inside the repentance translation file. There are empty lines that divide the ab+ changes from the new rep content

Thanks for the review. Do you have an estimation on when this will be deployed to the steam mod?

**Comment by wofsauge** [comment]
I will deploy it with the new feature im currently developing. I guess tomorrow or on saturday

**Comment by cagdassalur** [comment]
> I will deploy it with the new feature im currently developing. I guess tomorrow or on saturday

Sorry one more question, i didn't translate the names because i feel like it's against the game spirit, also makes it harder to search for items online. Is it currently possible to have a "#" in items name? So it can be like translated alternate name. If so i would like to add turkish names below it as well.

**Comment by wofsauge** [comment]
> Sorry one more question, i didn't translate the names because i feel like it's against the game spirit, also makes it harder to search for items online. Is it currently possible to have a "#" in items name? So it can be like translated alternate name. If so i would like to add turkish names below it as well.

Displaying the translated name of the items is an optional feature of the mod. Therefore the user himself can decide what he wants to see. There are currently 3 settings for that feature:
1. Display only English name
2. Display translated name (default)
3. Display both

In general, line breaks (#) are not supported in names, but since the name translation config option exist, its up to the user to display the translated name. If you want to translate them as well, go ahead :)

**Comment by cagdassalur** [comment]
> > Sorry one more question, i didn't translate the names because i feel like it's against the game spirit, also makes it harder to search for items online. Is it currently possible to have a "#" in items name? So it can be like translated alternate name. If so i would like to add turkish names below it as well.
> 
> Displaying the translated name of the items is an optional feature of the mod. Therefore the user himself can decide what he wants to see. There are currently 3 settings for that feature:
> 
>     1. Display only English name
> 
>     2. Display translated name (default)
> 
>     3. Display both
> 
> 
> In general, line breaks (#) are not supported in names, but since the name translation config option exist, its up to the user to display the translated name. If you want to translate them as well, go ahead :)

Ah i missed that option somehow, that's great to know :). I'll start on them as well.

**Pull request merged**
