### PR TITLE
Bag of Crafting fixed

### PR DESCRIPTION
**Pull request by Buurazu**
:)
I changed the bag to have its own "hide in battle" option that's true by default; I turned on hide in battle solely because of how awful it is with the bag, and I'm guessing I'm not alone.
Haven't ran into any bugs/inaccuracies except:
1. no clue at all how this works in co-op or with more than 1 bag of crafting active (would need a full rewrite to support either)
2. the active item version's 8-item preview doesn't always match if you picked up multiple items with your final swing; but there's nothing you can do at that point besides spawn what you made, so, it doesn't matter
3. bug with Schoolbag since right now I'm just checking for the player to press the active button with 8 items in bag (it's an instant activation that spawns a pedestal); but again, the only thing you can do at that point is empty the bag, so not an issue

if there's something wrong with the achievement warning still, it'd have to be a reproducible thing to debug it, I haven't ran into any issue now

todo: a hotkey for disabling the crafting display? (so you can see descriptions of other items still when you have bag, especially now that it's obtainable by normal characters that care about pedestal info)
a hotkey for previewing what you're about to craft? (mentioned in an Issue, I'm not that interested but eh)
simplified mode that gives quality total +  percentages of things rather than concrete recipes
I don't know how I want to approach the temporary disable hotkey though, I want it on the controller, not just another random key

### CODE REVIEW

**Comment by Buurazu** [comment]
I'm actually playing a normal run now with Cain to see if I have any problems, will edit:

Just got a desynced bag contents, possibly related to either me messing up the RT bag shifting, or maybe a blended heart order issue? (I picked it up with 7 things in bag)

**Comment by wofsauge** [comment]
Does this make bag of crafting work again on the newest patch dropped today? :)

**Comment by Buurazu** [comment]
Yeah, I already updated the new XMLData file
I feel like something already existed out there, but I made a little C# console app that takes the extracted item XMLs and outputs a lua file for use here, easy to update

I'm working on improving same-time-pickup accuracy (looks like blended hearts are ordered the wrong way for instance), gonna add a toggle bag overlay hotkey (F3 by default I guess?), simplified mode that doesn't spoil recipes, and an option to show recipes as 8 icons instead of the collapsed version

But for now, it's safe to get what's here out there to the masses

**Comment by wofsauge** [comment]
Awesome 👌 thanks for all the work you put into already ;)
I will hit up my vacation replacement person and ask for him to test and update the mod ;)

**Pull request merged**
