### PR TITLE
added 75 icons, reorganized icons, fixed most of the kerning on icons

### PR DESCRIPTION
**Pull request by biobak64**
• Added 67 new icons, including 44 handmade ones: bosses, chests, beggars, text-sized versions of existing icons and many more additions
• Reorganized the _eid_inline_icons.anm2_, _eid_inline_icons.png_ and _eid_data.lua_ files to be more consistent and better structured
• Fixed alignment and kerning on almost all icons so they have 1 visual pixel extra on each side, this way they don't clip into letters or other icons

image

image

### CODE REVIEW

**Comment by kohashiwakaba** [comment]
I've found that the icon color for `Quality3` and `Quality4` were swapped. This may cause some confusion for people who checks item qualities with the colors, especially Bag of Crafting recipes within EID.

**Comment by biobak64** [comment]
I was playing with the quality colors and forgot to reset them to the base colors. Fixed now!

**Comment by biobak64** [comment]
added text-sized icons for the curses

image

**Comment by wofsauge** [comment]
Great work

**Pull request merged**
